# list 基本操作

如何建立list

In [ ]:
a = list()
b = []
print(type(a))
print(type(b))

In [ ]:
x=list(1,2,3,4,5)
x

TypeError: ignored

In [ ]:
a = list((1,2,3,4,5))
a

[1, 2, 3, 4, 5]

In [ ]:
b = [1,2,3,4,5]
b

[1, 2, 3, 4, 5]

In [ ]:
c = [1,1.2,'C',"Hi",True,[1,2]]
c

[1, 1.2, 'C', 'Hi', True, [1, 2]]

list的元素可直接改變
位子從0開始

In [ ]:
x=[1,2,3]

In [ ]:
x[1]

2

In [ ]:
x[1]=5

In [ ]:
x

[1, 5, 3]

In [ ]:
x[3]=5

IndexError: ignored

取得list內某個位置的元素

In [ ]:
c = [1,1.2,'C',"Hi",True,[1,2]]

In [ ]:
type(c[0])

int

In [ ]:
type(c[1])

float

In [ ]:
type(c[4])

bool

In [ ]:
c[-1]

[1, 2]

In [ ]:
c[len(c)-1]

[1, 2]

In [ ]:
c[-2]

True

拿出list的多個元素 切片取值

In [ ]:
a = [1,2,3,4,5]

In [ ]:
#[起始位置:終止位置-1:間隔],預設[0:n-1:1]
a[1:3:1]

[2, 3]

In [ ]:
a[0:5:2]

[1, 3, 5]

巢狀list

In [ ]:
a = [1,2,3,[4,5,6,[3,3,4,[1,2]]],[2,3,6]]

In [ ]:
a

[1, 2, 3, [4, 5, 6, [3, 3, 4, [1, 2]]], [2, 3, 6]]

In [ ]:
a[3][3][3]

[1, 2]

In [ ]:
a[4]

[2, 3, 6]

# list的方法

## 基本（增加、減少）

在後方新增元素:append(想新增的元素)

In [ ]:
a=[1,2,3,4,5,6]

In [ ]:
a.append(10)

In [ ]:
a.append(11)

In [ ]:
a

[1, 2, 3, 4, 5, 6, 10, 11]

插入元素：insert(要插入的位置,要插入的元素)

In [ ]:
a = [1,2,3,4,5]

In [ ]:
a.insert(1,"Hi")

In [ ]:
a

[1, 'Hi', 2, 3, 4, 5]

移除元素:remove(要移除的元素)

In [ ]:
a = [1,2,3,4,5,6]

In [ ]:
a.remove(4)

In [ ]:
a

[1, 2, 3, 5, 6]

移除某個位置的元素：pop(想移除的位置)

In [ ]:
a=[1,2,3,4,5]

In [ ]:
a.pop(3)

4

In [ ]:
a

[1, 2, 3, 5]

## 更多方法

清空整個list:clear()

In [ ]:
a=[1,2,3]

In [ ]:
a

[1, 2, 3]

In [ ]:
a.clear()

In [ ]:
a

[]

取得list的長度：len(你的list)

In [ ]:
a=[1,2,3]

In [ ]:
len(a)

3

尋找某個元素的位置：index(要找的元素)

In [ ]:
a=[1,2,3,4,5]

In [ ]:
a.index(2)

1

In [ ]:
b=[1,2,2,3,3,3,4,3]

In [ ]:
b.index(2)

1

In [ ]:
b.index(3)

3

求某個元素出現的次數:count(要找的元素)

In [ ]:
a = [1,1,1,2,3,4,5,5,5,5,5]

In [ ]:
a.count(5)

5

針對list內的元素排序：sort()

In [1]:
a=[1,2,4,3,7,6,5]

In [2]:
a.reverse()

In [4]:
type(a)

list

In [ ]:
a.sort()

In [ ]:
a

[1, 2, 3, 4, 5, 6, 7]

In [ ]:
a.sort(reverse = True)

In [ ]:
a

[7, 6, 5, 4, 3, 2, 1]

In [ ]:
b=[1,2,3,"NCCU","hello"]

In [ ]:
b.sort()
b

TypeError: ignored

In [ ]:
c=["cow","apple","banana"]

In [ ]:
c.sort()
c

['apple', 'banana', 'cow']

In [ ]:
c.sort(reverse=True)
c

['cow', 'banana', 'apple']

# 補充：array(numpy.array) 陣列

https://www.w3schools.com/python/python_arrays.asp

array可處理多維度的資料（矩陣） 可做很多數學相關運算

一維陣列 vs list：1. array每一個元素都是相同的資料型態 2. array可直接做數學向量上的運算

長相：array([  ])

In [ ]:
import numpy as np

In [ ]:
onedim1=np.array([1,1,1])

In [ ]:
onedim1

array([1, 1, 1])

In [ ]:
type(onedim1)

numpy.ndarray

In [ ]:
onedim2==np.array([1,'e',1])
#Output:array(['1', 'e', '1'], dtype='<U21')-->1 converted to '1'

#Error example-->np.array([1,1,[1,1]])
#ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

list轉array轉list->casting

In [ ]:
a=[1,2,3,4,5]

In [ ]:
c=array(a)

NameError: ignored

In [ ]:
b=np.array(a)
b

array([1, 2, 3, 4, 5])

In [ ]:
c=list(b)
c

[1, 2, 3, 4, 5]

array可直接做運算

In [ ]:
d=onedim1+onedim1

In [ ]:
d*3

array([6, 6, 6])

In [ ]:
list1=[1,2,3,4,5]

[1, 2, 3, 4, 5]

In [ ]:
list1+list1

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [ ]:
list1*3

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [ ]:
i = np.arange(100)#1~99

In [ ]:
i

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

二維陣列（矩陣）

In [ ]:
twodim=np.array([[1,1,2],[2,2,4]])

In [ ]:
twodim

array([[1, 1, 2],
       [2, 2, 4],
       [2, 2, 2]])

# 補充：list.extend(list)

In [ ]:
a=[1,2,3,4,5]
b=[2,3,4,5]

In [ ]:
a.extend(b)#變更a=a+b
a

[1, 2, 3, 4, 5, 2, 3, 4, 5]

In [ ]:
a

[1, 2, 3, 4, 5, 2, 3, 4, 5]

# list的判斷(in & not in)

確認任何東西是否在list裡面

in & not in

In [ ]:
a = [1,2,3,4,5,[1,2,6]]
6 in a#if else for
6 in a[5]

In [ ]:
10 in a

False

In [ ]:
[1,2,3] in a
#False!
#Should be like[[1,2,3],4,5,[1,2,6]]

In [ ]:
a = [1,2,3]
print(1 in a)
print(4 in a)

True
False
